-- MySQL Script generated by MySQL Workbench
-- Sat Mar 12 15:26:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pharmacy_loyalty
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema pharmacy_loyalty
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy_loyalty` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `pharmacy_loyalty` ;

-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`userinfo` (
  `iduserinfo` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`iduserinfo`),
  INDEX `fk_userinfo_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_userinfo_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pharmacy_loyalty`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`support_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`support_line` (
  `idsupport_line` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `user_iduser` INT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`idsupport_line`),
  INDEX `fk_support_line_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_support_line_admin1_idx` (`admin_idadmin` ASC) VISIBLE,
  CONSTRAINT `fk_support_line_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pharmacy_loyalty`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_support_line_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `pharmacy_loyalty`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`loyalty_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`loyalty_levels` (
  `idloyalty_levels` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idloyalty_levels`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`loyalty_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`loyalty_card` (
  `idloyalty_card` INT NOT NULL,
  `open_date` VARCHAR(45) NOT NULL,
  `close_date` VARCHAR(45) NOT NULL,
  `bonus` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `loyalty_levels_idloyalty_levels` INT NOT NULL,
  PRIMARY KEY (`idloyalty_card`),
  INDEX `fk_loyalty_card_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_loyalty_card_loyalty_levels1_idx` (`loyalty_levels_idloyalty_levels` ASC) VISIBLE,
  CONSTRAINT `fk_loyalty_card_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pharmacy_loyalty`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loyalty_card_loyalty_levels1`
    FOREIGN KEY (`loyalty_levels_idloyalty_levels`)
    REFERENCES `pharmacy_loyalty`.`loyalty_levels` (`idloyalty_levels`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`card_operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`card_operations` (
  `idcard_operations` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL,
  `loyalty_card_idloyalty_card` INT NOT NULL,
  PRIMARY KEY (`idcard_operations`),
  INDEX `fk_card_operations_loyalty_card1_idx` (`loyalty_card_idloyalty_card` ASC) VISIBLE,
  CONSTRAINT `fk_card_operations_loyalty_card1`
    FOREIGN KEY (`loyalty_card_idloyalty_card`)
    REFERENCES `pharmacy_loyalty`.`loyalty_card` (`idloyalty_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy_loyalty`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy_loyalty`.`discounts` (
  `iddiscounts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `loyalty_levels_idloyalty_levels` INT NOT NULL,
  PRIMARY KEY (`iddiscounts`),
  INDEX `fk_discounts_loyalty_levels1_idx` (`loyalty_levels_idloyalty_levels` ASC) VISIBLE,
  CONSTRAINT `fk_discounts_loyalty_levels1`
    FOREIGN KEY (`loyalty_levels_idloyalty_levels`)
    REFERENCES `pharmacy_loyalty`.`loyalty_levels` (`idloyalty_levels`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
